name: Tests

on: pull_request

jobs:
  Tests:
    name: Run all tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version-file: '.nvmrc'

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm run tests
